services:
  - type: web
    name: django-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn osbase.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: osbase.settings
