# Generated by Django 4.2.21 on 2025-05-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGE', models.CharField(max_length=10)),
                ('BILL_ID', models.CharField(max_length=50, unique=True)),
                ('PROC_RESULT_CD', models.CharField(blank=True, max_length=20)),
                ('PROPOSER', models.CharField(blank=True, max_length=200)),
                ('DETAIL_LINK', models.URLField(blank=True)),
            ],
        ),
    ]
