# Generated by Django 4.2.21 on 2025-05-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGE', models.CharField(max_length=10)),
                ('BILL_ID', models.CharField(max_length=50, unique=True)),
                ('PROC_RESULT_CD', models.CharField(blank=True, max_length=20)),
                ('PROPOSER', models.CharField(blank=True, max_length=200)),
                ('DETAIL_LINK', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='AGE',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='DETAIL_LINK',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='PROC_RESULT_CD',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='PROPOSER',
        ),
        migrations.AddField(
            model_name='bill',
            name='CO_PROPOSERS',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='bill',
            name='MAIN_PROPOSER',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='bill',
            name='PROC_RESULT',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
