# Generated by Django 4.2.21 on 2025-05-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0002_all_remove_bill_age_remove_bill_detail_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposer', models.CharField(max_length=100, unique=True)),
                ('total', models.IntegerField(default=0)),
                ('approved', models.IntegerField(default=0)),
                ('discarded', models.IntegerField(default=0)),
                ('rejected', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPT_NM', models.CharField(blank=True, max_length=100)),
                ('JOB_RES_NM', models.CharField(blank=True, max_length=100)),
                ('HG_NM', models.CharField(max_length=100)),
                ('POLY_NM', models.CharField(blank=True, max_length=100)),
                ('MONA_CD', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('bill_id', models.CharField(max_length=100, unique=True)),
                ('proc_result_cd', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Costly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('bill_id', models.CharField(max_length=100, unique=True)),
                ('proc_result_cd', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
