# Generated by Django 4.2.21 on 2025-05-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0003_bill_count_committeemember_cost_costly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10)),
                ('bill_id', models.CharField(max_length=100, unique=True)),
                ('proc_result_cd', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=100, unique=True)),
                ('bill_no', models.CharField(blank=True, max_length=50)),
                ('bill_nm', models.TextField(blank=True)),
                ('proposer', models.CharField(blank=True, max_length=100)),
                ('proc_result_cd', models.CharField(blank=True, max_length=50)),
                ('announce_dt', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
