# Generated by Django 4.2.21 on 2025-05-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0005_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(max_length=50, unique=True)),
                ('member_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='assembly_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BILL_ID', models.CharField(max_length=50, unique=True)),
                ('BILL_NO', models.CharField(blank=True, max_length=50)),
                ('BILL_NAME', models.CharField(max_length=200)),
                ('PROPOSER', models.CharField(blank=True, max_length=200)),
                ('PROC_RESULT_CD', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PetitionIntroducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introducer_name', models.CharField(blank=True, max_length=200)),
                ('petition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legislation.petition')),
            ],
        ),
    ]
