# Generated by Django 4.2.21 on 2025-05-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0007_rename_assemblymember_photo_alter_bill_proc_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='CO_PROPOSERS',
            field=models.JSONField(default=list),
        ),
    ]
