# Generated by Django 4.2.21 on 2025-05-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0008_alter_bill_co_proposers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='CO_PROPOSERS',
            field=models.TextField(default='[]'),
        ),
    ]
