# Generated by Django 4.2.21 on 2025-05-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0010_etc_proc_result_date_alter_bill_count_proposer'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='rgs_proc_dt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='DETAIL_LINK',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='cost',
            name='rgs_proc_dt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='costly',
            name='DETAIL_LINK',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='costly',
            name='rgs_proc_dt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etc',
            name='DETAIL_LINK',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='etc',
            name='rgs_proc_dt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='DETAIL_LINK',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='law',
            name='rgs_proc_dt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='DETAIL_LINK',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='PROPOSE_DT',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
