# Generated by Django 4.2.21 on 2025-06-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0012_remove_etc_proc_result_date_alter_law_announce_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
