# Generated by Django 4.2.21 on 2025-06-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0013_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
