# Generated by Django 4.2.21 on 2025-06-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0014_alter_member_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
