# Generated by Django 4.2.21 on 2025-06-02 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0015_alter_member_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all',
            old_name='rgs_proc_dt',
            new_name='RGS_PROC_DT',
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='bill_id',
            new_name='BILL_ID',
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='proc_result_cd',
            new_name='PROC_RESULT_CD',
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='rgs_proc_dt',
            new_name='RGS_PROC_DT',
        ),
        migrations.RenameField(
            model_name='costly',
            old_name='bill_id',
            new_name='BILL_ID',
        ),
        migrations.RenameField(
            model_name='costly',
            old_name='proc_result_cd',
            new_name='PROC_RESULT_CD',
        ),
        migrations.RenameField(
            model_name='costly',
            old_name='rgs_proc_dt',
            new_name='RGS_PROC_DT',
        ),
        migrations.RenameField(
            model_name='etc',
            old_name='bill_id',
            new_name='BILL_ID',
        ),
        migrations.RenameField(
            model_name='etc',
            old_name='proc_result_cd',
            new_name='PROC_RESULT_CD',
        ),
        migrations.RenameField(
            model_name='law',
            old_name='bill_id',
            new_name='BILL_ID',
        ),
        migrations.RenameField(
            model_name='law',
            old_name='bill_nm',
            new_name='BILL_NM',
        ),
        migrations.RenameField(
            model_name='law',
            old_name='bill_no',
            new_name='BILL_NO',
        ),
    ]
