# Generated by Django 4.2.21 on 2025-06-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0016_rename_rgs_proc_dt_all_rgs_proc_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etc',
            old_name='rgs_proc_dt',
            new_name='RGS_PROC_DT',
        ),
        migrations.RenameField(
            model_name='law',
            old_name='proc_result_cd',
            new_name='PROC_RESULT_CD',
        ),
        migrations.RenameField(
            model_name='law',
            old_name='rgs_proc_dt',
            new_name='RGS_PROC_DT',
        ),
    ]
