# Generated by Django 4.2.21 on 2025-06-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0017_rename_rgs_proc_dt_etc_rgs_proc_dt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='law',
            old_name='announce_dt',
            new_name='ANNOUNCE_DT',
        ),
        migrations.RenameField(
            model_name='law',
            old_name='proposer',
            new_name='PROPOSER',
        ),
    ]
