# Generated by Django 4.2.21 on 2025-06-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0018_rename_announce_dt_law_announce_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='BILL_NM',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='bill',
            name='BILL_NM',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cost',
            name='BILL_NM',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='costly',
            name='BILL_NM',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='etc',
            name='BILL_NM',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
