# Generated by Django 4.2.21 on 2025-06-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0019_all_bill_nm_bill_bill_nm_cost_bill_nm_costly_bill_nm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='PROPOSER',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='costly',
            name='PROPOSER',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='etc',
            name='PROPOSER',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
