# Generated by Django 4.2.21 on 2025-06-02 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawmakerVoteSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('agree_count', models.PositiveIntegerField(default=0)),
                ('oppose_count', models.PositiveIntegerField(default=0)),
                ('invalid_or_abstain_count', models.PositiveIntegerField(default=0)),
                ('agree_and_passed', models.PositiveIntegerField(default=0)),
                ('oppose_and_failed', models.PositiveIntegerField(default=0)),
                ('lawmaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vote.lawmaker')),
            ],
        ),
    ]
