# Generated by Django 4.2.21 on 2025-06-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_lawmakervotesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawmakervotesummary',
            name='agree_and_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lawmakervotesummary',
            name='oppose_and_passed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
