# Generated by Django 4.2.21 on 2025-06-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vote', '0003_lawmakervotesummary_agree_and_failed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100)),
                ('total_score', models.FloatField()),
                ('attendance_score', models.FloatField()),
                ('bill_pass_score', models.FloatField()),
                ('petition_score', models.IntegerField()),
                ('petition_result_score', models.IntegerField()),
                ('committee_score', models.IntegerField()),
                ('invalid_vote_ratio', models.FloatField()),
                ('vote_match_ratio', models.FloatField()),
                ('vote_mismatch_ratio', models.FloatField()),
                ('lawmaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vote.lawmaker')),
            ],
        ),
    ]
