# Generated by Django 4.2.21 on 2025-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=100, unique=True)),
                ('avg_attendance', models.FloatField()),
                ('avg_invalid_vote_ratio', models.FloatField()),
                ('avg_vote_match_ratio', models.FloatField()),
                ('avg_vote_mismatch_ratio', models.FloatField()),
                ('bill_pass_sum', models.IntegerField()),
                ('petition_sum', models.IntegerField()),
                ('petition_pass_sum', models.IntegerField()),
                ('committee_leader_count', models.IntegerField()),
                ('member_count', models.IntegerField()),
                ('weighted_score', models.FloatField()),
            ],
        ),
    ]
