# Generated by Django 4.2.21 on 2025-06-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_partyperformance_attendance_pct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='bill_pass_score',
            new_name='bill_pass_count',
        ),
    ]
