# Generated by Django 4.2.21 on 2025-06-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_partyperformance_committee_secretary_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyperformance',
            name='avg_total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
